### ISSUE TITLE
TypeError: unsupported operand

### ISSUE THREAD

**Issue by fmalmeida** [Arkadiy-Garber/PseudoHunter#1]
Hi,

When trying to run the pipeline by mixing annotated genes and contigs as in

`PseudoHunter4.py -n genesNucleicAcids.ffn -a genesAminoAcids.faa -rn referenceNucleicAcids.ffn -ra referenceAminoAcids.faa -gff genes.gff -q contigs.fna -out PseudoHunter_output`

I get the following error:

```bash
Traceback (most recent call last):
  File "/Volumes/falmeida1TB/Pseudogene_Annotation/PseudoHunter/PseudoHunter4.py", line 619, in <module>
    outNUC.write(refFnaDict[ls[1]] + "\n")
TypeError: unsupported operand type(s) for +: 'collections.defaultdict' and 'str'
```

How it can be solved? Any ideas?

**Comment by Arkadiy-Garber** [comment]
Hi Felipe,

Thanks for using PseudoHunter! Sorry about that error. Any chance you could provide the genes.gff file, or just the first few lines, so that I could see the format of the contig and gene names? This program has shown instability before with regard to certain characters that are sometimes added to header names.

Thanks!
Arkadiy

**Comment by fmalmeida** [comment]
Yes, I can provide a small subset of the data, if necessary. Do you know if using repeat masked DNA sequences represents a problem for the pipeline?

The GFF looks like this

```bash
Scaffold_1      JGI     gene    22901   45904   .       +       .       ID=Beexcv11000001m.g;Name=Beexcv11000001m.g
Scaffold_1      JGI     mRNA    22901   45904   .       +       .       ID=PAC4GC:50510902;Name=Beexcv11000001m;longest=1;Parent=Beexcv11000001m.g
Scaffold_1      JGI     five_prime_UTR  22901   23284   .       +       .       ID=PAC4GC:50510902.five_prime_UTR.1;Parent=PAC4GC:50510902
Scaffold_1      JGI     CDS     23285   23423   .       +       0       ID=PAC4GC:50510902.CDS.1;Parent=PAC4GC:50510902
Scaffold_1      JGI     CDS     24031   24062   .       +       2       ID=PAC4GC:50510902.CDS.2;Parent=PAC4GC:50510902
Scaffold_1      JGI     CDS     24192   24254   .       +       0       ID=PAC4GC:50510902.CDS.3;Parent=PAC4GC:50510902
Scaffold_1      JGI     CDS     24509   24568   .       +       0       ID=PAC4GC:50510902.CDS.4;Parent=PAC4GC:50510902
Scaffold_1      JGI     CDS     37558   37603   .       +       0       ID=PAC4GC:50510902.CDS.5;Parent=PAC4GC:50510902
Scaffold_1      JGI     CDS     37775   37821   .       +       2       ID=PAC4GC:50510902.CDS.6;Parent=PAC4GC:50510902
Scaffold_1      JGI     CDS     37927   38228   .       +       0       ID=PAC4GC:50510902.CDS.7;Parent=PAC4GC:50510902
Scaffold_1      JGI     CDS     42345   42702   .       +       1       ID=PAC4GC:50510902.CDS.8;Parent=PAC4GC:50510902
Scaffold_1      JGI     CDS     42798   43343   .       +       0       ID=PAC4GC:50510902.CDS.9;Parent=PAC4GC:50510902
Scaffold_1      JGI     CDS     44798   45079   .       +       0       ID=PAC4GC:50510902.CDS.10;Parent=PAC4GC:50510902
```

Any ideas?

**Comment by Arkadiy-Garber** [comment]
Thanks, the repeat masked DNA sequences should not be a problem.

Could you try re-running the program with the same command that you used, but add the `-delim .` flag. (make sure -delim is followed by one period "."). And let me know if that solves the issue. If not, if you could provide a small subset of the ffn and faa files used, that would be great.

Thanks!
Arkadiy

**Comment by fmalmeida** [comment]
Well, it did not work. I'll send you a super small subset of the data at `agarber4@asu.edu` so you can get the gist of the data formatting. I hope it can help on solving the problem.

**Comment by Arkadiy-Garber** [comment]
Ok, sounds good. You can also upload it here, if that is easier.

Thanks!
Arkadiy
